
#ifndef ConstValues_h
#define ConstValues_h
FOUNDATION_EXPORT NSString *const CASPER_ERROR_MESSAGE_NONE;
FOUNDATION_EXPORT NSString *const CASPER_RPC_METHOD_GET_STATE_ROOT_HASH;
FOUNDATION_EXPORT NSString *const CASPER_RPC_METHOD_INFO_GET_PEERS;
FOUNDATION_EXPORT NSString *const CASPER_RPC_METHOD_INFO_GET_DEPLOY;
FOUNDATION_EXPORT NSString *const CASPER_RPC_METHOD_INFO_GET_STATUS;
FOUNDATION_EXPORT NSString *const CASPER_RPC_METHOD_CHAIN_GET_BLOCK_TRANSFERS;
FOUNDATION_EXPORT NSString *const CASPER_RPC_METHOD_CHAIN_GET_BLOCK;
FOUNDATION_EXPORT NSString *const CASPER_RPC_METHOD_CHAIN_GET_ERA_BY_SWITCH_BLOCK;
FOUNDATION_EXPORT NSString *const CASPER_RPC_METHOD_STATE_GET_ITEM;
FOUNDATION_EXPORT NSString *const CASPER_RPC_METHOD_STATE_GET_DICTIONARY_ITEM;
FOUNDATION_EXPORT NSString *const CASPER_RPC_METHOD_STATE_GET_BALANCE;
FOUNDATION_EXPORT NSString *const CASPER_RPC_METHOD_STATE_GET_AUCTION_INFO;
FOUNDATION_EXPORT NSString *const CASPER_RPC_METHOD_ACCOUNT_PUT_DEPLOY;

//CLType
FOUNDATION_EXPORT NSString *const CLTYPE_BOOL;
FOUNDATION_EXPORT NSString *const CLTYPE_I32;
FOUNDATION_EXPORT NSString *const CLTYPE_I64;
FOUNDATION_EXPORT NSString *const CLTYPE_U8;
FOUNDATION_EXPORT NSString *const CLTYPE_U32;
FOUNDATION_EXPORT NSString *const CLTYPE_U64;
FOUNDATION_EXPORT NSString *const CLTYPE_U128;
FOUNDATION_EXPORT NSString *const CLTYPE_U256;
FOUNDATION_EXPORT NSString *const CLTYPE_U512;
FOUNDATION_EXPORT NSString *const CLTYPE_UNIT;
FOUNDATION_EXPORT NSString *const CLTYPE_STRING;
FOUNDATION_EXPORT NSString *const CLTYPE_KEY;
FOUNDATION_EXPORT NSString *const CLTYPE_UREF;
FOUNDATION_EXPORT NSString *const CLTYPE_PUBLICKEY;
FOUNDATION_EXPORT NSString *const CLTYPE_OPTION;
FOUNDATION_EXPORT NSString *const CLTYPE_LIST;
FOUNDATION_EXPORT NSString *const CLTYPE_BYTEARRAY;
FOUNDATION_EXPORT NSString *const CLTYPE_RESULT;
FOUNDATION_EXPORT NSString *const CLTYPE_MAP;
FOUNDATION_EXPORT NSString *const CLTYPE_TUPLE1;
FOUNDATION_EXPORT NSString *const CLTYPE_TUPLE2;
FOUNDATION_EXPORT NSString *const CLTYPE_TUPLE3;
FOUNDATION_EXPORT NSString *const CLTYPE_ANY;

#endif
