#ifndef Deploy_h
#define Deploy_h
#import <Foundation/Foundation.h>
#import "DeployHeader.h"
#import "ExecutableDeployItem.h"
/**Class built for storing Deploy information
 */
@interface Deploy:NSObject
@property NSString * itsHash;
@property NSMutableArray * approvals;
@property DeployHeader * header;
@property ExecutableDeployItem * payment;
@property ExecutableDeployItem * session;
/**This function parse the Dictionary object (as part of the JSON object taken from server RPC method call) to Deploy object
 */
+(Deploy*) fromJsonDictToDeploy:(NSDictionary*) fromDict;
-(void) logInfo;
/** This function generate the String parameter used for account_put_deploy RPC call, base on the deploy information itself, to send the deploy to the account_put_deploy RPC method*/
-(NSString*) toPutDeployParameterStr;
/**
 Get body hash of a deploy
 - Returns: String represent the body hash of the deploy. The hash is generated by using blake2b256b hash over the concatenation of payment serialization + session serialization
 */

-(NSString*) getBodyHash;
/**
 Get header hash of a deploy
 - Parameter : a deploy header
 - Returns: String represent the body hash of the deploy header. The hash is generated by using blake2b256b hash over the header serialization.
 */
-(NSString *) getDeployHash;
@end

#endif
